apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    uid: clickhouse-rag-logs
    isDefault: true
    editable: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: rag_logs
      username: default
      tlsSkipVerify: false
    secureJsonData:
      password: ""
